//Standar for create a new permission:
// 1. All the name of the permissions must be in uppercase.
// 1. The first part of the name must be the module name.
// 2. The second part of the name must be the action that the permission allows.

export const PERMISSIONS = [
  /* MODULE USER ADMINISTRATION ONLY ADMIN OF SISTEMA */
  { name: 'USER-ADMINISTRATION-CAN-CREATE-PERMISSIONS' },
  { name: 'USER-ADMINISTRATION-CAN-LIST-PERMISSIONS' },
  { name: 'USER-ADMINISTRATION-CAN-UPDATE-PERMISSIONS' },
  { name: 'USER-ADMINISTRATION-CAN-DELETE-PERMISSIONS' },
  { name: 'USER-ADMINISTRATION-CAN-SEE-MODULE-USERS-ADMINISTRATION'},
  { name: 'USER-ADMINISTRATION-CAN-LIST-USERS'},
  { name: 'USER-ADMINISTRATION-CAN-UPDATE-USERS'},
  { name: 'USER-ADMINISTRATION-CAN-CREATE-USERS'},
  { name: 'USER-ADMINISTRATION-CAN-DELETE-USERS'},
  { name: 'USER-ADMINISTRATION-CAN-LIST-ROLES'},
  { name: 'USER-ADMINISTRATION-CAN-UPDATE-ROLES'},
  { name: 'USER-ADMINISTRATION-CAN-CREATE-ROLES'},
  { name: 'USER-ADMINISTRATION-CAN-DELETE-ROLES'},
  
  /* MODULE MEMBER ADMINISTRATION */
  { name: 'MEMBER-ADMINISTRATION-CAN-SEE-MODULE-MEMBER-ADMINISTRATION' },
  { name: 'MEMBER-ADMINISTRATION-CAN-CREATE-MEMBER-CLUB' },
  
  /* MODULE PRODUCTS ADMINISTRATION */
  { name: 'CAN-SEE-MODULE-PRODUCTS-ADMINISTRATION' },

  /* MODULE SALES BOX */
  { name: 'CAN-SEE-MODULE-SALES-BOX'},
]